name: counter_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/bomb.png
    - assets/case0.png
    - assets/case1.png
    - assets/case2.png
    - assets/case3.png
    - assets/case4.png
    - assets/case5.png
    - assets/case6.png
    - assets/case7.png
    - assets/case8.png
    - assets/explosion.png
    - flag.png
